//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics.CodeAnalysis;

namespace Mapping.Shapes
{
    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.1.
    // 
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage()]
    public partial class vmscid
    {

        private long vmscnoField;

        /// <remarks/>
        public long vmscno
        {
            get
            {
                return this.vmscnoField;
            }
            set
            {
                this.vmscnoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage()]
    public partial class time
    {

        private short utc_offField;

        private long valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short utc_off
        {
            get
            {
                return this.utc_offField;
            }
            set
            {
                this.utc_offField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public long Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage()]
    public partial class svc_result
    {

        private slia sliaField;

        private string verField;

        /// <remarks/>
        public slia slia
        {
            get
            {
                return this.sliaField;
            }
            set
            {
                this.sliaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ver
        {
            get
            {
                return this.verField;
            }
            set
            {
                this.verField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage()]
    public partial class slia
    {

        private pos posField;

        private string verField;

        /// <remarks/>
        public pos pos
        {
            get
            {
                return this.posField;
            }
            set
            {
                this.posField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ver
        {
            get
            {
                return this.verField;
            }
            set
            {
                this.verField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage()]
    public partial class poserr
    {

        private result resultField;

        private time timeField;

        /// <remarks/>
        public result result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }

        /// <remarks/>
        public time time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage()]
    public partial class result
    {

        private short residField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short resid
        {
            get
            {
                return this.residField;
            }
            set
            {
                this.residField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage()]
    public partial class pos
    {

        private long msidField;

        private pd pdField;

        private gsm_net_param gsm_net_paramField;

        private poserr poserrField;

        /// <remarks/>
        public long msid
        {
            get
            {
                return this.msidField;
            }
            set
            {
                this.msidField = value;
            }
        }

        /// <remarks/>
        public pd pd
        {
            get
            {
                return this.pdField;
            }
            set
            {
                this.pdField = value;
            }
        }

        /// <remarks/>
        public gsm_net_param gsm_net_param
        {
            get
            {
                return this.gsm_net_paramField;
            }
            set
            {
                this.gsm_net_paramField = value;
            }
        }


        /// <remarks/>
        public poserr poserr
        {
            get
            {
                return this.poserrField;
            }
            set
            {
                this.poserrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage()]
    public partial class pd
    {

        private time timeField;

        private shape shapeField;

        /// <remarks/>
        public time time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }

        /// <remarks/>
        public shape shape
        {
            get
            {
                return this.shapeField;
            }
            set
            {
                this.shapeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage()]
    public partial class shape
    {

        private CircularArea circularAreaField;

        private CircularArcArea circularArcAreaField;

        private Polygon polygonField;

        /// <remarks/>
        public CircularArea CircularArea
        {
            get
            {
                return this.circularAreaField;
            }
            set
            {
                this.circularAreaField = value;
            }
        }

        /// <remarks/>
        public CircularArcArea CircularArcArea
        {
            get
            {
                return this.circularArcAreaField;
            }
            set
            {
                this.circularArcAreaField = value;
            }
        }

        /// <remarks/>
        public Polygon Polygon
        {
            get
            {
                return this.polygonField;
            }
            set
            {
                this.polygonField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage()]
    public partial class CircularArcArea
    {

        private coord coordField;

        private int inRadiusField;

        private int outRadiusField;

        private short startAngleField;

        private short sweepAngleField;

        /// <remarks/>
        public coord coord
        {
            get
            {
                return this.coordField;
            }
            set
            {
                this.coordField = value;
            }
        }

        /// <remarks/>
        public int inRadius
        {
            get
            {
                return this.inRadiusField;
            }
            set
            {
                this.inRadiusField = value;
            }
        }

        /// <remarks/>
        public int outRadius
        {
            get
            {
                return this.outRadiusField;
            }
            set
            {
                this.outRadiusField = value;
            }
        }

        /// <remarks/>
        public short startAngle
        {
            get
            {
                return this.startAngleField;
            }
            set
            {
                this.startAngleField = value;
            }
        }

        /// <summary>
        /// The stopAngle is really how many degrees the arc sweeps through
        /// From the spec: The stop angle is the angle (in angularUnit) between the first and second defined radius.
        /// http://docbox.etsi.org/STF/Archive/STF321_TISPAN3_EC_Emergency_Call_Location/Public/Library/OMA%20Documents/OMA%20Mobile%20Location%20Protocol%20V3_2-20051124-c.pdf
        /// </summary>
        [System.Xml.Serialization.XmlElement("stopAngle")]
        public short sweepAngle
        {
            get
            {
                return this.sweepAngleField;
            }
            set
            {
                this.sweepAngleField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage()]
    public partial class CircularArea
    {

        private coord coordField;

        private short radiusField;

        /// <remarks/>
        public coord coord
        {
            get
            {
                return this.coordField;
            }
            set
            {
                this.coordField = value;
            }
        }

        /// <remarks/>
        public short radius
        {
            get
            {
                return this.radiusField;
            }
            set
            {
                this.radiusField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage()]
    public partial class Polygon
    {

        private outerBoundaryIs outerBoundaryIsField;

        /// <remarks/>
        public outerBoundaryIs outerBoundaryIs
        {
            get
            {
                return this.outerBoundaryIsField;
            }
            set
            {
                this.outerBoundaryIsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage()]
    public partial class outerBoundaryIs
    {

        private coord[] linearRingField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("coord", IsNullable = false)]
        public coord[] LinearRing
        {
            get
            {
                return this.linearRingField;
            }
            set
            {
                this.linearRingField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage()]
    public partial class coord
    {

        private OmaCoordinate xField;

        private OmaCoordinate yField;

        /// <remarks/>
        public OmaCoordinate X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        public OmaCoordinate Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage()]
    public partial class OmaCoordinate
    {
        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage()]
    public partial class gsm_net_param
    {

        private neid neidField;

        /// <remarks/>
        public neid neid
        {
            get
            {
                return this.neidField;
            }
            set
            {
                this.neidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage()]
    public partial class neid
    {

        private vmscid vmscidField;

        /// <remarks/>
        public vmscid vmscid
        {
            get
            {
                return this.vmscidField;
            }
            set
            {
                this.vmscidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ExcludeFromCodeCoverage]
    public partial class LinearRing
    {

        private coord[] coordField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("coord")]
        public coord[] coord
        {
            get
            {
                return this.coordField;
            }
            set
            {
                this.coordField = value;
            }
        }
    }

}
