// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RadioMessagesProcessor.Helpers;

namespace radioMessagesProcessor.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181124035705_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RadioMessagesProcessor.Entities.RadioLocationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CollectionDateUTC");

                    b.Property<DateTime>("DecodedDateUTC");

                    b.Property<byte[]>("DecodedEvent");

                    b.Property<double>("DecodedLatitude");

                    b.Property<double>("DecodedLongitude");

                    b.Property<DateTime>("DeviceDate");

                    b.Property<double>("GpsAccuracy");

                    b.Property<long>("GpsAge");

                    b.Property<double?>("GpsBearing");

                    b.Property<double>("GpsLatitude");

                    b.Property<double>("GpsLongitude");

                    b.Property<double>("GpsSpeed");

                    b.Property<string>("Imei");

                    b.Property<byte[]>("RawEvent");

                    b.Property<int>("Rssi");

                    b.HasKey("Id");

                    b.ToTable("RadioLocationMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
