//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapping {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mapping.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character &apos;{0:x2}&apos; is encountered..
        /// </summary>
        internal static string Argument_Base32InvalidCharacter {
            get {
                return ResourceManager.GetString("Argument_Base32InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is not defined for the enum {1}..
        /// </summary>
        internal static string Argument_EnumValueNotDefined {
            get {
                return ResourceManager.GetString("Argument_EnumValueNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect array length ({0}) expected {1}..
        /// </summary>
        internal static string Argument_IncorrectArrayLength {
            get {
                return ResourceManager.GetString("Argument_IncorrectArrayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array length is expected to be between {0} and {1} but is actually {2}..
        /// </summary>
        internal static string Argument_IncorrectArrayLengthRange {
            get {
                return ResourceManager.GetString("Argument_IncorrectArrayLengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not the correct type for the parameter.  Expected type {1}..
        /// </summary>
        internal static string Argument_IncorrectType {
            get {
                return ResourceManager.GetString("Argument_IncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid identifier - GUID version 9 is required. First nibble of the sixth octet is set to 0x9 and octets 8 and 9 are set to 0x80 and 0x00 respectively..
        /// </summary>
        internal static string Argument_InvalidGuid {
            get {
                return ResourceManager.GetString("Argument_InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid object identifier format..
        /// </summary>
        internal static string Argument_InvalidIdentifierFormat {
            get {
                return ResourceManager.GetString("Argument_InvalidIdentifierFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array length must be at most {0} but is actually {1}..
        /// </summary>
        internal static string Argument_MaximumArrayLength {
            get {
                return ResourceManager.GetString("Argument_MaximumArrayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array length must be at least {0} but is actually {1}..
        /// </summary>
        internal static string Argument_MinimumArrayLength {
            get {
                return ResourceManager.GetString("Argument_MinimumArrayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be greater than value..
        /// </summary>
        internal static string Argument_MustBeGreaterThan {
            get {
                return ResourceManager.GetString("Argument_MustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be greater than or equal to value..
        /// </summary>
        internal static string Argument_MustBeGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("Argument_MustBeGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be of type ObjectIdentifier..
        /// </summary>
        internal static string Argument_MustBeObjectIdentifier {
            get {
                return ResourceManager.GetString("Argument_MustBeObjectIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has been cancelled because EndOfData has been signaled.
        /// </summary>
        internal static string Cancelled_EndOfData {
            get {
                return ResourceManager.GetString("Cancelled_EndOfData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is empty..
        /// </summary>
        internal static string CollectionIsEmpty {
            get {
                return ResourceManager.GetString("CollectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting remote content: {0}.
        ///Location: {1}.
        /// </summary>
        internal static string ErrorGettingRemoteContent {
            get {
                return ResourceManager.GetString("ErrorGettingRemoteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty object identifier cannot be converted to a canonical string..
        /// </summary>
        internal static string Format_EmptyObjectIdentifier {
            get {
                return ResourceManager.GetString("Format_EmptyObjectIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format string can be only &quot;C&quot;, &quot;c&quot;..
        /// </summary>
        internal static string Format_InvalidNodeIdentifierFormatSpecification {
            get {
                return ResourceManager.GetString("Format_InvalidNodeIdentifierFormatSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format string can be only &quot;G&quot;, &quot;g&quot;, &quot;C&quot;, &quot;c&quot;, &quot;O&quot;, &quot;o&quot;..
        /// </summary>
        internal static string Format_InvalidObjectIdentifierFormatSpecification {
            get {
                return ResourceManager.GetString("Format_InvalidObjectIdentifierFormatSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Guid object identifier cannot converted to a canonical string..
        /// </summary>
        internal static string Format_LegacyGuidObjectIdentifier {
            get {
                return ResourceManager.GetString("Format_LegacyGuidObjectIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided IAsyncResult is invalid..
        /// </summary>
        internal static string Invalid_AsyncResult {
            get {
                return ResourceManager.GetString("Invalid_AsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data can not be popped off the stack once the end of data has been reached..
        /// </summary>
        internal static string Invalid_EndOfDataSignaled {
            get {
                return ResourceManager.GetString("Invalid_EndOfDataSignaled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OPC provider supplied..
        /// </summary>
        internal static string Invalid_OPC_Provider {
            get {
                return ResourceManager.GetString("Invalid_OPC_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Node Identifier retrieved from storage..
        /// </summary>
        internal static string InvalidNodeIdFoundInStorage {
            get {
                return ResourceManager.GetString("InvalidNodeIdFoundInStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude must be between -90 and 90.
        /// </summary>
        internal static string LattitudeOutOfRangeError {
            get {
                return ResourceManager.GetString("LattitudeOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude must be between -180 and 180.
        /// </summary>
        internal static string LongitudeOutOfRangeError {
            get {
                return ResourceManager.GetString("LongitudeOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support reading..
        /// </summary>
        internal static string NotSupported_UnreadableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnreadableStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support seeking..
        /// </summary>
        internal static string NotSupported_UnseekableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnseekableStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support writing..
        /// </summary>
        internal static string NotSupported_UnwritableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnwritableStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Descriptor class must implement default constructor..
        /// </summary>
        internal static string ResourceDescriptor_NoDefaultConstructor {
            get {
                return ResourceManager.GetString("ResourceDescriptor_NoDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Stack.Pop operation has timed out after {0} ms..
        /// </summary>
        internal static string Timeout_PopOffStack {
            get {
                return ResourceManager.GetString("Timeout_PopOffStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be assignable from  {1}..
        /// </summary>
        internal static string TypeA_NotAssignableFrom_TypeB {
            get {
                return ResourceManager.GetString("TypeA_NotAssignableFrom_TypeB", resourceCulture);
            }
        }
    }
}
